"""baseline_current_schema

Revision ID: 0cdade4da8ba
Revises: 
Create Date: 2026-08-28 14:17:53.557069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdade4da8ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)

    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('od_sph_original', sa.Float(), nullable=False),
    sa.Column('od_cyl_original', sa.Float(), nullable=True),
    sa.Column('od_axis_original', sa.Integer(), nullable=True),
    sa.Column('od_add', sa.Float(), nullable=True),
    sa.Column('od_sph', sa.Float(), nullable=False),
    sa.Column('od_cyl', sa.Float(), nullable=True),
    sa.Column('od_axis', sa.Integer(), nullable=True),
    sa.Column('os_sph_original', sa.Float(), nullable=False),
    sa.Column('os_cyl_original', sa.Float(), nullable=True),
    sa.Column('os_axis_original', sa.Integer(), nullable=True),
    sa.Column('os_add', sa.Float(), nullable=True),
    sa.Column('os_sph', sa.Float(), nullable=False),
    sa.Column('os_cyl', sa.Float(), nullable=True),
    sa.Column('os_axis', sa.Integer(), nullable=True),
    sa.Column('transposition_applied', sa.Boolean(), nullable=True),
    sa.Column('pd', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_id'), ['id'], unique=False)

    op.create_table('catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('processing_errors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogs_id'), ['id'], unique=False)

    op.create_table('lens_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('lens_code', sa.String(length=50), nullable=True),
    sa.Column('category', sa.Enum('SINGLE_VISION', 'BIFOCAL', 'PROGRESSIVE', 'OFFICE', 'DIGITAL', name='lenscategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lens_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lens_models_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lens_models_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_lens_models_lens_code'), ['lens_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_lens_models_name'), ['name'], unique=False)

    op.create_table('catalog_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('extracted_name', sa.String(length=200), nullable=False),
    sa.Column('extracted_category', sa.String(length=50), nullable=True),
    sa.Column('extracted_material', sa.String(length=50), nullable=True),
    sa.Column('extracted_index', sa.Float(), nullable=True),
    sa.Column('extracted_availability', sa.String(length=20), nullable=True),
    sa.Column('sph_min', sa.Float(), nullable=True),
    sa.Column('sph_max', sa.Float(), nullable=True),
    sa.Column('cyl_min', sa.Float(), nullable=True),
    sa.Column('cyl_max', sa.Float(), nullable=True),
    sa.Column('add_min', sa.Float(), nullable=True),
    sa.Column('add_max', sa.Float(), nullable=True),
    sa.Column('extracted_price', sa.Float(), nullable=True),
    sa.Column('extracted_features', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('modified_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_extractions_id'), ['id'], unique=False)

    op.create_table('lens_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lens_model_id', sa.Integer(), nullable=False),
    sa.Column('material', sa.Enum('CR39', 'POLYCARBONATE', 'TRIVEX', 'HIGH_INDEX_156', 'HIGH_INDEX_160', 'HIGH_INDEX_161', 'HIGH_INDEX_167', 'HIGH_INDEX_174', name='materialtype'), nullable=False),
    sa.Column('index_value', sa.Float(), nullable=False),
    sa.Column('availability', sa.Enum('STOCK', 'RX', 'BOTH', name='lensavailability'), nullable=False),
    sa.Column('design_type', sa.Enum('SPHERICAL', 'ASPHERICAL', 'DOUBLE_ASPHERICAL', 'FREE_FORM', name='designtype'), nullable=True),
    sa.Column('is_aspherical', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lens_model_id'], ['lens_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lens_variants', schema=None) as batch_op:
        batch_op.create_index('idx_variant_aspherical', ['is_aspherical'], unique=False)
        batch_op.create_index('idx_variant_model_index', ['lens_model_id', 'index_value'], unique=False)
        batch_op.create_index('idx_variant_model_material', ['lens_model_id', 'material'], unique=False)
        batch_op.create_index(batch_op.f('ix_lens_variants_id'), ['id'], unique=False)

    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('index_recommended', sa.Boolean(), nullable=True),
    sa.Column('aspherical_recommended', sa.Boolean(), nullable=True),
    sa.Column('stock_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['lens_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_results_id'), ['id'], unique=False)

    op.create_table('power_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lens_model_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('sph_min', sa.Float(), nullable=False),
    sa.Column('sph_max', sa.Float(), nullable=False),
    sa.Column('cyl_min', sa.Float(), nullable=False),
    sa.Column('cyl_max', sa.Float(), nullable=False),
    sa.Column('add_min', sa.Float(), nullable=True),
    sa.Column('add_max', sa.Float(), nullable=True),
    sa.Column('axis_min', sa.Integer(), nullable=True),
    sa.Column('axis_max', sa.Integer(), nullable=True),
    sa.Column('max_cyl_for_high_sph', sa.Float(), nullable=True),
    sa.Column('sph_threshold', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lens_model_id'], ['lens_models.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['lens_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('power_ranges', schema=None) as batch_op:
        batch_op.create_index('idx_power_add', ['add_min', 'add_max'], unique=False)
        batch_op.create_index('idx_power_cyl', ['cyl_min', 'cyl_max'], unique=False)
        batch_op.create_index('idx_power_sph', ['sph_min', 'sph_max'], unique=False)
        batch_op.create_index('idx_power_variant', ['variant_id', 'sph_min', 'sph_max'], unique=False)
        batch_op.create_index(batch_op.f('ix_power_ranges_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('power_ranges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_power_ranges_id'))
        batch_op.drop_index('idx_power_variant')
        batch_op.drop_index('idx_power_sph')
        batch_op.drop_index('idx_power_cyl')
        batch_op.drop_index('idx_power_add')

    op.drop_table('power_ranges')
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_results_id'))

    op.drop_table('match_results')
    with op.batch_alter_table('lens_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lens_variants_id'))
        batch_op.drop_index('idx_variant_model_material')
        batch_op.drop_index('idx_variant_model_index')
        batch_op.drop_index('idx_variant_aspherical')

    op.drop_table('lens_variants')
    with op.batch_alter_table('catalog_extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_extractions_id'))

    op.drop_table('catalog_extractions')
    with op.batch_alter_table('lens_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lens_models_name'))
        batch_op.drop_index(batch_op.f('ix_lens_models_lens_code'))
        batch_op.drop_index(batch_op.f('ix_lens_models_is_active'))
        batch_op.drop_index(batch_op.f('ix_lens_models_id'))

    op.drop_table('lens_models')
    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogs_id'))

    op.drop_table('catalogs')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_is_active'))
        batch_op.drop_index(batch_op.f('ix_companies_id'))

    op.drop_table('companies')
    # ### end Alembic commands ###
